image: docker:19.03.13-dind

stages:  # - test
  - build

before_script:
  - apk add openjdk11
  - apk add sbt --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
  - sbt sbtVersion  ## print installed version

test:
  stage: test
  script:
    - sbt clean coverage test coverageReport

build:
  stage: build
  script:
    - docker image ls
    #- sbt docker:stage
