image: docker:19.03.13-dind

stages:
  - test
  - build

before_script:
  - apk add openjdk11 sbt
  - sbt sbtVersion  ## print installed version

test:
  stage: test
  script:
    - sbt clean coverage test coverageReport

build:
  stage: build
  script:
    - sbt docker:stage
