image: docker:latest

services:
  - docker:dind

stages:
# - test
  - build

#before_script:
#  - apk add openjdk11
#  - apk add sbt --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
#  - sbt sbtVersion  ## print installed version

#test:
#  stage: test
#  script:
#    - sbt clean coverage test coverageReport

build:
  stage: build
  script:
    - DOCKER_HOST=tcp://docker:2375 docker info
    #- sbt docker:stage
