image: alpine:latest

stages:
# - test
  - build-dockerfile
  - build-dockerimage

#before_script:
#  - apk add openjdk11
#  - apk add sbt --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
#  - sbt sbtVersion  ## print installed version

#test:
#  stage: test
#  script:
#    - sbt clean coverage test coverageReport

build-dockerfile:
  stage: build-dockerfile
  script:
    - apk add openjdk11
    - apk add sbt --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
    - sbt sbtVersion  # print installed version
    - sbt docker:stage  # package the application
  artifacts:
    paths:
      - target/docker/stage
    expire_in: 1 hour

build-dockerimage:
  stage: build-dockerimage
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    #mgit/base:kaniko-executor-debug-stable
    #gcr.io/kaniko-project/executor:debug-v0.16.0
    #gcr.io/kaniko-project/executor:debug  # see https://docs.gitlab.com/ce/ci/docker/using_kaniko.html
    entrypoint: [""]
  script:
    # With vanilla docker you would be using:
    # docker build --tag poca-2020:latest --file target/docker/stage/Dockerfile target/docker/stage
    - mkdir -p /kaniko/.docker
    - echo $CI_REGISTRY_CREDENTIALS
    - echo $CI_REGISTRY_TOKEN
    - echo $CI_REGISTRY_CREDENTIALS | base64
    - echo $CI_REGISTRY_TOKEN | base64
    - export CI_REGISTRY_TOKEN=abc
    - echo "{\"auths\":{\"https://index.docker.io/v2/\":{\"auth\":\"`echo -n poca:$CI_REGISTRY_TOKEN | base64`\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context target/docker/stage --dockerfile target/docker/stage/Dockerfile --destination poca-2020:latest

    #- sbt docker:stage
